### ISSUE TITLE
Reflect App Mesh object state in status

### ISSUE THREAD

**Issue by nckturner** [aws/aws-app-mesh-controller-for-k8s#11]
In order to clean up objects in App Mesh when custom resources are deleted (#10), we need to reflect those objects state in the status field for custom resources.  App Mesh resources currently have their own `Status` field, which can be `ACTIVE`, `INACTIVE`, or `DELETED`.  My current thoughts are we can have one of:

* a condition for each of these possible states (each condition value can be `True`, `False`, or `Unknown`),
* or a top level `appMeshStatus` which just reflects the App Mesh status.

I am leaning towards using a condition for each state, because although its a bit of a strange translation, it reflects the direction that the Kubernetes API is moving (conditions instead of things like Pod phase).  Its also easier to add conditions without breaking client assumptions if the App Mesh API changes in the future or we want to add other similar states.

**Comment by astrived** [comment]
This is addressed as part of 0.5.0
