### ISSUE TITLE
Proposal: Add Support to IAM Roles For Service Account - EKS

### ISSUE THREAD

**Issue by shreyasmm** [aws/aws-app-mesh-controller-for-k8s#110]
Right now i am adding the below policy to EKS worker nodes to work with App Mesh
````json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "servicediscovery:DeregisterInstance",
                "route53:CreateHealthCheck",
                "route53:ChangeResourceRecordSets",
                "route53:GetHealthCheck",
                "route53:UpdateHealthCheck",
                "route53:DeleteHealthCheck",
                "servicediscovery:RegisterInstance",
                "servicediscovery:GetService",
                "appmesh:*",
                "servicediscovery:CreateService",
                "servicediscovery:ListInstances"
            ],
            "Resource": "*"
        }
    ]
}
````

[AWS EKS](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/),  [AWS SDK](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html), [Cluster AutoScaler](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.14.6) already support IAM Roles for Service Accounts

Is it possible to add support to App Mesh Controller

**Comment by kiranmeduri** [comment]
Controller uses AWS sdk under the hood so it should already support IRSA. Is it not working?

**Comment by M00nF1sh** [comment]
this is already addressed in our GA version.
Our helm chart documentation have steps to use iam-for-service-accounts.
