### ISSUE TITLE
Manage Cloud Map service life-cycle

### ISSUE THREAD

**Issue by kiranmeduri** [aws/aws-app-mesh-controller-for-k8s#131]
#107

Cloud Map services are created automatically by controller, but not deleted. Partly this is because, creating is a safe operation, while deleting is not due to ownership model. There can be multiple actors who may be using this service, say multi-cluster, ECS-EKS, etc. Without coordination it may not be safe to remove. This needs a design proposal.

**Comment by M00nF1sh** [comment]
we can add tagging to cloudmap(if it supports), or add label/finalizers to virtual node :D

**Comment by astrived** [comment]
@achevuru is going to look at this issue

**Comment by achevuru** [comment]
We will be handling this as part of v1.0 GA.

**Comment by M00nF1sh** [comment]
this is addressed in GA. the controller will delete the cloudMap service if it's created by controller.
We identify the ownership by using virtualNode's UUID as cloudMapService's creatorRequestID
