### ISSUE TITLE
all.yaml inconsistent with Helm chart

### ISSUE THREAD

**Issue by efe-selcuk** [aws/aws-app-mesh-controller-for-k8s#136]
### Summary
`deploy/all.yaml` contains both the CRDs as well as supporting bits for running the controller like a ClusterRole. Some of the identifiers in there are slightly inconsistent with the Helm chart, which means a developer following the development guide may set up the controller with Helm, then apply `all.yaml` and get two copies of the controller and other resources.

The one case I unblocked myself with was renaming the ClusterRole from `app-mesh-controller` to `appmesh-controller` to be able to apply the leader election permissions that the chart does not yet have. I haven't checked the other fields.

It's also probably appropriate to split the CRDs into a separate file as that's what service team members will likely be touching, maybe leveraging kustomization to apply both (I'm not familiar).

**Comment by achevuru** [comment]
1.0 GA image and it's corresponding helm chart will not have this issue. CRDs will be available as separate files under config.
