### ISSUE TITLE
[minor] property spec.listeners.portMapping should mark to required in the CRD definition

### ISSUE THREAD

**Issue by zhiyanliu** [aws/aws-app-mesh-controller-for-k8s#139]
**An issue report:**
Current CRD definition allows user defines a vnode resource without  any portMapping in a listeners, as the result, even it can pass the k8s validation at API resource creation stage,  however error logs [0] are printed by the controller in each reconciling.

[0] error syncing 'namespace/virtualnode-resource': error adding finalizer virtualNodeDeletion.finalizers.appmesh.k8s.aws to virtual node virtualnode-resource-namespace: VirtualNode.appmesh.k8s.aws "virtualnode-resource" is invalid: []: Invalid value: validation failure list:
spec.listeners.portMapping.protocol in body should be one of [tcp http grpc http2 https]

**Software versions:**
`appmesh k8s controller`:
Version: v0.4.0
GitCommit: 8e976927ff6b13a8f51883c5584f697f62d0729d
BuildDate: 2020-03-13T05:56:58Z
GoVersion: go1.13.8
Compiler: gc
Platform: linux/amd64
`kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bcelenza** [comment]
Additionally, `https` is not a valid value (this field is used for the protocol, not the scheme).
