### ISSUE TITLE
Version not incremented in previous release

### ISSUE THREAD

**Issue by nckturner** [aws/aws-app-mesh-controller-for-k8s#141]
Usually we bump this version in each release: https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/Makefile#L9

In the v0.4.0 release it wasn't bumped.  We should make the change and add a release process document/readme, then rebuild the containers so the print the correct version.  

Alternatively we could modify the build to use the most recent git tag, but regardless we should re-do the v0.4.0 release.

**Comment by M00nF1sh** [comment]
will make a change to address this.
But don't panic, version in image & log is correct, i passed version to makefile when build xD.
