### ISSUE TITLE
Pods don't get auto registered/deregistered in kubernetes with Cloud Map

### ISSUE THREAD

**Issue by pksinghus** [aws/aws-app-mesh-controller-for-k8s#159]
**Summary**
When I scale up the deployment behind a VirtualNode in kubernetes, the additional pods don’t get registered with Cloud Map. Similarly, while scaling down the IP addresses/service instances stay registered with the service and have to be manually deregistered.

**Steps to Reproduce**
Create a Cloud Map namespace pointing to the VPC of EKS cluster
Create a mesh
Deploy any sample that works with Cloud Map as service discovery
Scale up the deployment
Additional pods/IP addresses created are not registered as service instances in Cloud Map
Scale down the deployment
Pods/IP addresses stay registered in Cloud Map

**Are you currently working around this issue?**
No.

**Additional context**

**Attachments**
[manifest.yaml.txt](https://github.com/aws/aws-app-mesh-roadmap/files/3986186/manifest.yaml.txt)

This manifest can be deployed as an example. Auto registration of pods doesn't happen. Cloud Map namespace is assumed to be `dj-cloudmap.pvt.aws.local`

**Comment by kiranmeduri** [comment]
Tagging this issue as a GA fix.

**Comment by efe-selcuk** [comment]
Woops, misclick. I ran into this today but I'm not sure how to repro. I had a test standing up a bunch of pods and noticed the controller wasn't catching up; I killed the test, all the pods were torn down, but many instances were still registered in the namespace. I didn't see additional logs and request metrics showed they died down to 0.

This might be easier to repro if #160 is indeed an issue as we can reliably repro that the controller doesn't catch up.

**Comment by efe-selcuk** [comment]
If the mesh doesn't exist, we seemingly won't handle cloudmap teardown.

That doesn't explain registration or address part of the original issue here, but it's related.

**Comment by achevuru** [comment]
Will be addressed in v1.0 GA release.

**Comment by achevuru** [comment]
Fixed in v1.0.
