### ISSUE TITLE
v1beta1 RetryPolicy fields incorrectly marked as optional

### ISSUE THREAD

**Issue by efe-selcuk** [aws/aws-app-mesh-controller-for-k8s#161]
`MaxRetries` and `PerRetryTimeout` are required for both HttpRetryPolicy and GrpcRetryPolicy

- https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_GrpcRetryPolicy.html
  - https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/apis/appmesh/v1beta1/types.go#L263-L266
- https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_HttpRetryPolicy.html
  - https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/apis/appmesh/v1beta1/types.go#L193-L196

The go types are incorrect and they are not marked required in the schema validation in the CRDs (though there are more examples of the latter).

[v1beta2](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/v1beta2/apis/appmesh/v1beta2/virtualrouter_types.go#L248-L252) is [correct](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/v1beta2/apis/appmesh/v1beta2/virtualrouter_types.go#L137-L140). Recording this in case we want to fix it in this version.

**Comment by astrived** [comment]
since v1beta2 has a fix we will not address it unless we make another 0.5.x release.

**Comment by jamsajones** [comment]
We will not fix this in v1beta1
