### ISSUE TITLE
Metrics show continuous calls to various write APIs

### ISSUE THREAD

**Issue by efe-selcuk** [aws/aws-app-mesh-controller-for-k8s#171]
Similar to #160 when there are cloud map services created, the controller seems to repeatedly call CreateService.

![Screen Shot 2020-04-22 at 3 08 23 PM](https://user-images.githubusercontent.com/3759279/80038758-1e3fe780-84ab-11ea-80e5-5664f41a6944.png)

There's other things mixed in that screenshot but effectively it's that flat-ish line from 14:40 onward.

I thought maybe it was the same issue as with RegisterInstance of relying on the create call for idempotency, but at a glance, the code seems to cache the service.

- https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/aws/cloudmap.go#L45
- https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/aws/cloudmap.go#L134

It's possible the cache isn't getting populated due to some error but without debug logging I don't know.

**Comment by efe-selcuk** [comment]
I'm actually going to change this to cover multiple APIs, as I'm also seeing somewhat consistent write calls to app mesh on master, without corresponding write throttles.

![Screen Shot 2020-04-22 at 6 22 49 PM](https://user-images.githubusercontent.com/3759279/80048916-70423680-84c6-11ea-91ce-8389de3562b5.png)

**Comment by astrived** [comment]
@achevuru has addressed this as part of 1.0 GA release.

**Comment by achevuru** [comment]
Will be addressed as part of v1.0 GA release

**Comment by achevuru** [comment]
Fixed in upcoming v1.0 release.
