### ISSUE TITLE
Add parameter for x-ray sidecar image

### ISSUE THREAD

**Issue by rafaelpereyra** [aws/aws-app-mesh-controller-for-k8s#287]
Hello,

When dealing with a single source of truth for the Image repository (Single shared ECR account for example), it's important to be able to specify the images to be deployed on each environment. 

The injector currently allows to specify the images for:

- Injector
- Envoy
- Proxy-route-manager

However for the X-Ray image it uses a fixed github repo defined in xrayDaemonContainerTemplate.

The injection of the X-Ray sidecar is very useful and provides an easy integration path between both services (App-Mesh / X-Ray) so it will be very useful to have this additional parameter so there is no need to load the sidecar manually and leave the default repo as default value just like the other images.

**Comment by M00nF1sh** [comment]
we should expose a configurability for this

**Comment by fawadkhaliq** [comment]
x-ray sidecar image is configurable now https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/313 thanks @cmdallas
