### ISSUE TITLE
Injection for egress-only pods

### ISSUE THREAD

**Issue by PaulMaddox** [aws/aws-app-mesh-controller-for-k8s#292]
The current documentation is really confusing for pods that only have egress-only traffic.

Injection only occurs when a pod has ports set (which by default are grabbed from the pod container definition), however in an egress-only scenario these won't be set.

The documentation is not clear as to whether I should annotate with         `appmesh.k8s.aws/ports`, or whether this is just for ingress.

**Comment by M00nF1sh** [comment]
@PaulMaddox 
Egress-only pods is already supported for pods running on EC2 nodes.

For pods running with EKS on Fargate, there is a pending bugFix needed by ECS team, which is tracked by https://github.com/aws/aws-app-mesh-controller-for-k8s/issues/263.

Closing this issue
