### ISSUE TITLE
Generate cert at startup

### ISSUE THREAD

**Issue by stefanprodan** [aws/aws-app-mesh-controller-for-k8s#293]
To simplify the install, if no cert is provided by the user, the admission controller could generate a self signed cert at startup with `MaybeDefaultWithSelfSignedCerts` https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/serving.go#L271

Here is an example https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/sample-apiserver/pkg/cmd/server/start.go#L108

**Comment by M00nF1sh** [comment]
closing this as both cert-manager/bash script is supported in GA version
