### ISSUE TITLE
AppMesh Envoy Sidecar initialisation issues

### ISSUE THREAD

**Issue by rjl79** [aws/aws-app-mesh-controller-for-k8s#294]
I'm trying to get the latest sidecar image running `aws-appmesh-envoy:v1.12.2.1-prod` so we can take advantage of IRSA for credentials, however this never seems to fully initialise, and routing outside of the pod is not possible, with destination unreachable.
The appmesh injector pods seems to run correctly, and is injecting the appropriate pod updates, but it seems a permission issue in the injected service account token. If I exec into the envoy container, I am unable to view the token.

```
bash-4.2$ cat /var/run/secrets/eks.amazonaws.com/serviceaccount/token
cat: /var/run/secrets/eks.amazonaws.com/serviceaccount/token: Permission denied
bash-4.2$ whoami
whoami: cannot find name for user ID 1337
```

This is also the case for the x-ray agent. 

This appears to be reported here as a general issue with non-root container users unable to view the service account token. 
https://github.com/aws/amazon-eks-pod-identity-webhook/issues/8

The workaround is to add 
```
      securityContext:
        fsGroup: 65534
```
to the spec, but I have been unable to verify this.

**Comment by M00nF1sh** [comment]
this is already addressed in GA version. 
We automatically patch a PodSecurityContext if absents to use this iam for service accounts feature
