### ISSUE TITLE
[Enhancement] Add more client-side validation via our validatingWebhook

### ISSUE THREAD

**Issue by M00nF1sh** [aws/aws-app-mesh-controller-for-k8s#295]
We should add more client-side validation via our validatingWebhook

**Comment by fawadkhaliq** [comment]
Client side validation for open issues (https://github.com/aws/aws-app-mesh-controller-for-k8s/issues/135) has been added here #331. In this change:

- VirtualNode validator will check for duplicate backend references (VirtualServiceRefs & VirtualServiceARNs) and reject them on create/update
- VirtualRouter validator will check for duplicate route entries and reject them on create/update
