### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by mhausenblas** [aws/aws-app-mesh-controller-for-k8s#30]
For convenience, it would be nice to have a Helm chart that takes care of deploying the controller and manage other lifecycle-related tasks.

**Comment by PaulMaddox** [comment]
I have created the following helm charts:

 - `aws-appmesh-inject` (includes CA and certificate generation via [this approach](https://medium.com/nuvo-group-tech/move-your-certs-to-helm-4f5f61338aca))
 - `aws-appmesh-controller`

I'm also creating two others:

 - `aws-appmesh-prometheus` (configured to scrape envoy endpoints)
 - `aws-appmesh-grafana` (with preconfigured dashboards for meshes)

I'm going to create a helm meta-chart called `aws-appmesh` that installs and configures all of the above in a single command.

I have a few questions:

 - Should the helm chart sources be hosted in this repository? (even though they contain a chart for the injector), in the official helm repo, or should we create a new aws repository for the helm charts (my preference).

 - The helm charts will need to be regenerated whenever an update of `amazon/app-mesh-controller`, `amazon/aws-app-mesh-inject`, `amazon/aws-app-mesh-inject`, `aws-appmesh-envoy` or `aws-appmesh-proxy-route-manager` are updated. Is there a build pipeline already in place for this project? If so, can you provide details (if it's internal, chime me: pmaddox@)

**Comment by mhausenblas** [comment]
@nckturner might want to re-assign this to @PaulMaddox?

> Should the helm chart sources be hosted in this repository? (even though they contain a chart for the injector), in the official helm repo, or should we create a new aws repository for the helm charts (my preference).

Yeah, I think we should have a dedicated repo, not sure if we already have Helm charts somewhere, otherwise how about `aws/helm-charts`? Then, to make it a little more readable, we could apply for `charts.aws` and submit that to the Hub?

> Is there a build pipeline already in place for this project? If so, can you provide details (if it's internal, chime me: pmaddox@)

I believe @nckturner can talk to that. The two of us will sync tomorrow anyways and follow up via Chime, yes.

**Comment by PaulMaddox** [comment]
It's done 🎉

Check out https://github.com/PaulMaddox/aws-appmesh-helm

There's a detailed README that walks you through deploying, and includes screenshots etc.

It does need us to merge https://github.com/aws/aws-app-mesh-inject/pull/49 though, as currently it's using a forked version of amazon/aws-app-mesh-inject.

One simple `helm install` gets you the injector, controller, X-Ray, as well as prometheus and grafana dashboards (global mesh and per-service) 😎

<img width="1438" alt="appmesh-dashboard-overview" src="https://user-images.githubusercontent.com/4678446/57753731-f45c3d80-76fd-11e9-98ae-790e5774fdaf.png">

<img width="1437" alt="appmesh-dashboard-per-service" src="https://user-images.githubusercontent.com/4678446/57753750-fc1be200-76fd-11e9-94d3-8d327e734724.png">

**Comment by nckturner** [comment]
@PaulMaddox Do we want to get this chart into helm/stable?

**Comment by nckturner** [comment]
Ok so after speaking with @stefanprodan, it seems that charts/stable is not the place to put it anymore.  We should create a separate repository, and link it to helm hub so that it is still discoverable.

**Comment by stefanprodan** [comment]
@mhausenblas  this can be closed, the App Mesh charts are hosted on the EKS Helm repository here https://github.com/aws/eks-charts
