### ISSUE TITLE
Add arm64 architecture support

### ISSUE THREAD

**Issue by scottmalkie** [aws/aws-app-mesh-controller-for-k8s#318]
Referencing the larger request here: https://github.com/aws/aws-app-mesh-roadmap/issues/215 

Requesting official arm64 architecture support for the K8s controller so that it doesn't become a blocker for App Mesh arm64 support as whole.

Thanks!

**Comment by fawadkhaliq** [comment]
arm support will be added in the subsequent releases. Removing the 1.3.0 milestone

**Comment by alexbilbie** [comment]
@fawadkhaliq is there an update on this issue?

**Comment by fawadkhaliq** [comment]
hello @alexbilbie, this is pending on: https://github.com/aws/aws-app-mesh-roadmap/issues/215
