### ISSUE TITLE
Can not access sts in a private eks cluster

### ISSUE THREAD

**Issue by SeliMeli** [aws/aws-app-mesh-controller-for-k8s#328]
When using appmesh at private eks (cluster dont have access to internet), at the set up of appmesh controller, it will try to get account id from sts.amazonaws.com which is not accessable. But we have created an endpiont at vpc with private dns (sts.region.amazonaws.com). Is there any way to change the hostname when appmesh controller set up?
![image](https://user-images.githubusercontent.com/9347182/89282773-99a25f00-d67e-11ea-8cd6-d618213f7500.png)
(and set aws-account-id not work nither at deploy yaml

**Comment by fawadkhaliq** [comment]
@SeliMeli thanks for filing the issue. The account id issue has been fixed here #330 

For the STS endpoint, appmesh controller does not currently support overriding it. We will add the support for overriding the endpoint

**Comment by SeliMeli** [comment]
I think the point is the controller ignored region config I passed to it. Because normally, when region is set, it should use region host instead of global host.

**Comment by fawadkhaliq** [comment]
@SeliMeli @jane829 we will expose the STS endpoint in 1.1.1 release. However, you might run into limitations in terms of what App Mesh supports with VPC endpoints. Please see this issue [1] for details. And please upvote this [1] if you would like support for VPC endpoints for App Mesh

[1] https://github.com/aws/aws-app-mesh-roadmap/issues/208

**Comment by fawadkhaliq** [comment]
You can override STS endpoint using https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/339. Please note App Mesh for private EKS clusters will not work unless this [1] is resolved. Please consider upvoting 

[1] aws/aws-app-mesh-roadmap#208

**Comment by fawadkhaliq** [comment]
The original issue #330 in the chain wasn't the reason to reach the global STS endpoint. #339  was added to provide a way to override the STS endpoint of choice, however, this can also be achieved using PrivateLink, where it will set the dns for public STS endpoint in the VPC. We will recommend going with the latter approach and rely on PrivateLink endpoints that should match the same DNS names as the public regional endpoints, therefore reverting this
