### ISSUE TITLE
Multi-cluster multi-VPC mesh support

### ISSUE THREAD

**Issue by stefanprodan** [aws/aws-app-mesh-controller-for-k8s#33]
To accommodate a mesh that spans across clusters I see two options:

1. Allow virtual nodes/services to refer a mesh that's not defined in the Kubernetes cluster but exists in App Mesh
2. Discover existing meshes and create "readonly" Kubernetes objects

For both approaches handling the mesh deletion is problematic.

**Comment by athilaelhuno** [comment]
Hello, any updates about multi-cluster support.
I would like reach a virtual services in the same mesh but different cluster.
Is that possible?

**Comment by nckturner** [comment]
Since App Mesh doesn't support tagging yet (to my knowledge), we can add an "owner" field to the mesh custom resource, and only if it is set to true would be attempt to create or delete the mesh itself.  Otherwise, we just look for it.

**Comment by efe-selcuk** [comment]
@nckturner App Mesh has supported tagging since we went GA, including tag-on-create; you're referring to AWS tagging right? Is that a path forward to address this?

**Comment by nckturner** [comment]
@efe-selcuk Yeah my mistake, we can use tags then as well. I think that's a better solution.

**Comment by kiranmeduri** [comment]
I have few clarifying questions that may help find the solution.

1. In a multi-cluster mode, is each cluster using its own VPC or are they sharing same VPC? 
2. If they have individual VPCs then how is the connectivity established? (peering, transit-gw, privatelink,...)
3. What is the service-discovery solution across cluster? Cloud Map HttpNamespace should work across VPC boundaries, and so does App Mesh EDS. However, registration of proper endpoints behind the service does not include enough metadata to support split-horizon discovery.

**Comment by athilaelhuno** [comment]
For my case:
1.- I have 2 EKS clusters in different VPC.
2.- I am not using peering, transit-gw. 
3.- I did not know I needed another service to discover the services when I use APP Mesh. I supposed when I expose the virtualservice I could reach that service using that.

Please I would like to know what is the best way to connect my services, because all the documentation says for one cluster.

**Comment by shubharao** [comment]
We do have guidance on setting up multi EKS cluster with peered VPCs [here](https://aws.amazon.com/blogs/containers/cross-amazon-eks-cluster-app-mesh-using-aws-cloud-map/) and we have plans to launch support for a mesh across one VPC with multiple AWS accounts [coming soon](https://github.com/aws/aws-app-mesh-roadmap/issues/64)

**Comment by athilaelhuno** [comment]
Thx for you support I did it using Cloudmap and so far so good

**Comment by M00nF1sh** [comment]
This is resolved in GA version.
It's possible to use two VPC with peered connection and using cloudmap as serviceDiscovery.

**Comment by benpettman** [comment]
I am using the lates version of the controller (1.0.0) and when I have 2 clusters with 1 vpc and I deploy the mesh components to one cluster and then try to deploy the front end app to the other cluster, the mutating webhook denies the deployment as it cannot find a matching virtualnode, which is on the other cluster for it.

The previously mentioned blog post is what I followed, but that seems to be for the older controller. I am using CloudMap, but cant get that far as the controller wont even allow the deployment to deploy.

What am I missing?
