### ISSUE TITLE
UPGRADE FAILED to enable X-Ray tracing

### ISSUE THREAD

**Issue by sunao-uehara** [aws/aws-app-mesh-controller-for-k8s#333]
I was trying to enable X-Ray tracing for AppMesh on my eks cluster, so followed official [instruction](https://aws.github.io/aws-app-mesh-controller-for-k8s/guide/tracing/) to run following command.

```
>helm upgrade -i appmesh-controller eks/appmesh-controller \
    --namespace appmesh-system \
    --set tracing.enabled=true \
    --set tracing.provider=x-ray
```

But I got this error, and it seems I need to add some extra annotation/label to appmesh-controller's pod beforehand?
```
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: ServiceAccount "appmesh-controller" in namespace "appmesh-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "appmesh-controller"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "appmesh-system"
```

Anybody is having same issue?

**Comment by achevuru** [comment]
@sunao-uehara It appears that you have some lingering resources from your previous installation of the controller(pre GA version?). You can try to delete them prior to re attempting the helm install.

"rendered manifests contain a resource that already exists. Unable to continue with update: ServiceAccount "appmesh-controller" in namespace "appmesh-system" exists and cannot be imported into the current release"

**Comment by sunao-uehara** [comment]
Hi @achevuru,

I am sure the controller's version is latest as v1.1.0 as I installed it about a week ago, but I re-installed it from scratch and tried upgrading it with X-Ray Tracing enable. Actually It worked! I am not sure what was wrong in the end. I keep watching and re-open this issue if I found suspicious issue.

Thanks
