### ISSUE TITLE
Introduce installation/startup checks in the controller

### ISSUE THREAD

**Issue by dastbe** [aws/aws-app-mesh-controller-for-k8s#334]
Looking at issues like #328, it would be nice if we could codify our expectations for running the controller (STS availability, App Mesh API availability, iptables modification, etc.) into a command that runs on controller installation or on-demand by customers to determine the suitability of their cluster. Not only does it give us the opportunity to give customers early warning about whether their installation will work, but also gives us a mechanism to proactively direct them to remediation steps.

**Comment by achevuru** [comment]
Controller does have installation time validation builtin. Current behavior/validation is summarized below.

- Validates all the configurable parameters passed to the controller
- Validates multiple tracers are not enabled at the same time ( https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/inject/config.go#L76)
- Errors out if incorrect API version is used in App Mesh CRD/Specs
- Will exit if an incorrect STS endpoint is specified (indirectly validates values passed in for Region and Account ID)
- Logs valid error messages in controller logs, if required permissions are missing

Controller is not involved with any iptable related operations and therefore doesn’t require access to modify iptables. Controller is also not running across all the worker nodes in a cluster. ‘Proxy Init’ container that gets included as an init container in each of the pod specs will be assigned appropriate permissions for it to be able to setup required iptable rules for envoy.
