### ISSUE TITLE
Reusing a VirtualNode name results in stale Envoy configuration

### ISSUE THREAD

**Issue by jqmichael** [aws/aws-app-mesh-controller-for-k8s#35]
Summary

When deleting and re-creating a VirtualNode with the same name (e.g. my-virtual-node under a Mesh named my-mesh), an Envoy identified as that VirtualNode name (e.g. mesh/my-mesh/virtualNode/my-virtual-node) which connects shortly after re-creating the VirtualNode may receive the previous VirtualNode's configuration. 

This typically happens when you repeatedly start and tear down your application with the same names. 

App Mesh team is working on a solution for this bug that will periodically check for this state and request the Envoy to reconnect to receive updated configuration.

Related App Mesh bugs.  
https://github.com/aws/aws-app-mesh-roadmap/issues/49
https://github.com/aws/aws-app-mesh-roadmap/issues/50

**Comment by dastbe** [comment]
The following changes have been made to App Mesh

1. We currently reconcile your configuration periodically (on the order of seconds), even over literal Virtual Node changes as described above
2. When a node is deleted for over 5 minutes, we will purge its configuration entirely from our downstream systems. Previously, this took on the order of 7 days.
