### ISSUE TITLE
Jaeger tracing broken with App Mesh Envoy v1.15.0.0-prod

### ISSUE THREAD

**Issue by Y0Username** [aws/aws-app-mesh-controller-for-k8s#353]
While using App Mesh Envoy version `v1.15.0.0-prod` Jaeger tracing is broken due to regression.

Envoy is looking for the Jaeger tracing config in the env variable `ENVOY_TRACING_CFG_FILE`.
But the k8s controller puts the config in the env variable pointed by `ENVOY_STATS_CONFIG_FILE`.

The relevant code is [here](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/fa911c740ffcf835a44a4ef71346b152308ffc41/pkg/inject/envoy.go#L54)

The fix is to to pass the Jaeger tracing config for Envoy version `v1.15.0.0-prod` using the env variable `ENVOY_TRACING_CFG_FILE`

**Comment by fawadkhaliq** [comment]
App Mesh Envoy bootstrap in Envoy version `v1.12.5.0-prod` was merging tracing config from `ENVOY_STATS_CONFIG_FILE` and this was changed in Envoy `v1.15.0.0-prod`. 

Controller will be updated to use the flag `ENVOY_TRACING_CFG_FILE` in 1.2.0. Workaround is to use Envoy version `v1.12.5.0-prod`

**Comment by achevuru** [comment]
#359
