### ISSUE TITLE
Allow service instance port to be specified in Cloud Map service discovery

### ISSUE THREAD

**Issue by rifqialabqary** [aws/aws-app-mesh-controller-for-k8s#357]
I'm trying to expose EKS services via Amazon API Gateway (HTTP API) through private integration using AWS Cloud Map service discovery.

If I understand correctly, through the App Mesh Controller, only the pods IP addresses will be registered.
However, API Gateway needs both IP addresses and ports in order to work when using AWS Cloud Map private integration as stated [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-private.html#http-api-develop-integrations-private-Cloud-Map).

Using the following, I am able to register both the IP addresses and ports in AWS Cloud Map. And I am able to connect to the EKS pods through API Gateway.

```
serviceDiscovery:
  awsCloudMap:
    namespaceName: ${CLOUDMAP_NAMESPACE}
    serviceName: ${CLOUDMAP_SERVICE}
    attributes:
    - key: "AWS_INSTANCE_PORT"
      value: "${APP_PORT}"
```

However, although Custom Resources in Kubernetes are created, resources in App Mesh are not being created and logs in the controller shows the following:

```
{
  "level": "error",
  "ts": 1601945565.5024025,
  "logger": "controller-runtime.controller",
  "msg": "Reconciler error",
  "controller": "virtualnode",
  "request": "eems-coe/eems-auth-service",
  "error": "BadRequestException: AWS CloudMap Service Discovery Attribute Key AWS_INSTANCE_PORT can not use the reserved AWS_ prefix.",
  "stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n /go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n /go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n /go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n /go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"
}
```

And I think this cause the connection become unstable as API Gateway sometimes sent `503 Service Unavailable` response after new deployment.

Is there any other way to specify the port for Cloud Map service discovery?

**Comment by cgchinmay** [comment]
Changes are merged so closing the Issue.
