### ISSUE TITLE
[Doc] Link the cross-cluster example in the live docs

### ISSUE THREAD

**Issue by fawadkhaliq** [aws/aws-app-mesh-controller-for-k8s#390]
**Describe the bug**
The [cross-cluster App Mesh example](https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-k8s-cross-cluster) isn't linked in the live docs [walkthroughs](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/docs/tutorials/walkthroughs.md)

**Steps to reproduce**
N/A - doc is missing 

**Expected outcome**
Doc link should be present in the live doc

**Environment**
N/A

* App Mesh controller version: >=v1.0.0
* Envoy version: N/A
* Are you using any integrations? X-ray, Jaeger etc. If so versions? N/A
* Kubernetes version: N/A
* Using EKS (yes/no), if so version? Yes

**Additional Context**:

**Comment by cgchinmay** [comment]
Closing the Issue as changes have been merged
