### ISSUE TITLE
We should have health check added for App Mesh controller

### ISSUE THREAD

**Issue by haouc** [aws/aws-app-mesh-controller-for-k8s#407]
**Is your feature request related to a problem?**
A description of what the problem is. For example: I'm frustrated when [...]
We don't have something like /healthz added for App Mesh controller. we should have this liveness probe added and we can monitor the healthy status of the controller.

**Describe the solution you'd like**
A description of what you want to happen.
I want the health check being added, endpoint exposed and available for monitoring the status of App Mesh controller.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by achevuru** [comment]
Addressed via #410
