### ISSUE TITLE
Problem upgrading app mesh.

### ISSUE THREAD

**Issue by proca-ainq** [aws/aws-app-mesh-controller-for-k8s#416]
We were using version 0.5, wiped it out entirely, ran the upgrade check script and then deployed 1.2.1 and we're seeing:

`Failed to list *v1beta2.VirtualService: request to convert CR from an invalid group/version: appmesh.k8s.aws/v1beta1`

on the controller pod.  When we try to actually deploy a service using the sidecar injection, it fails with the same error.  I've wiped out almost everything from the cluster and we are still getting this error after reinstalling.  

I'm posting here because no google searches are yielding any hits on an error like this.   I don't understand how it's still seeing `appmesh.k8s.aws/v1beta1` after we wiped out all the CRDs that reference it.  The upgrade script reported that everything passed and we were ready to upgrade.   

Environment

App Mesh controller version v1.2.1
Kubernetes version v1.15
Using EKS (yes/no), if so version? yes, 1.15

**Comment by fawadkhaliq** [comment]
hi @proca-ainq, were you following the upgrade instructions here [1] ?

[1] https://github.com/aws/eks-charts/tree/master/stable/appmesh-controller#upgrade

**Comment by proca-ainq** [comment]
Yes, I cleared everything to almost bare metal and ran instructions as if we had never installed it and we still got the error.  Then we tried upgrading EKS/k8s to 1.18 and still got the error. 

We finally just rebuilt the cluster from scratch on 1.18 and it works now.    I'll close my issue since it is no longer a problem for us.
