### ISSUE TITLE
Feature request: Ability to pass through arbitrary environment variables from AppMesh controller to pods

### ISSUE THREAD

**Issue by brettlangdon** [aws/aws-app-mesh-controller-for-k8s#428]
**Is your feature request related to a problem?**
We would like the ability to set arbitrary tags on the Envoy containers in our mesh in order to customize Datadog tracing.

In order to control the `env` tag that is associated with the traces produced we need the ability to set the `DD_ENV=prod` environment variable on our Envoy containers.

**Describe the solution you'd like**
We would like the ability to define arbitrary environments variables that can be applied to Envoy containers.

**Describe alternatives you've considered**

**Comment by jseiser** [comment]
We are having this same problem.  All of our traces come in with a proper environment, except Appmesh/Envoy, which come in as environment=none.

**Comment by fawadkhaliq** [comment]
Thanks for filing the issue

@jseiser @brettlangdon I see there are three potential levels of env config granularity: cluster, namespace, and pod. In the environments you're using, are the env variables global to the cluster or namespace/pod or mixed?

**Comment by jseiser** [comment]
In our case, `DD_ENV` is mixed.

On say, a production cluster, all apps are sending DD_ENV=production, but on the QA cluster, you would have multiple apps sending DD_ENV=qa1, and other sending DD_ENV=qa2 etc.

Now, for every application that has an envoy sidecar, we are setting DD_ENV, as an ENV variable. So if we could do something like, annotating our app, with ENV Vars we want app mesh to have, that would work perfect.

**Comment by fawadkhaliq** [comment]
@jseiser great, this is helpful! A mix of global (controller params) + per pod annotation makes sense

**Comment by fawadkhaliq** [comment]
We'll add support for this in the next controller release 1.3.0

**Comment by fawadkhaliq** [comment]
Fixed here: https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/429 -- will be included in the next release
