### ISSUE TITLE
Bug: deleting and recreating mesh with the same name throws TLS error

### ISSUE THREAD

**Issue by kenichi-shibata** [aws/aws-app-mesh-controller-for-k8s#447]
*SECURITY NOTICE: If you think you’ve found a potential security issue, please do not post it in the Issues. Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com).*

**Summary**
Creation -> Deletion -> Creation of Mesh with the same name throws

```
remote error: tls: bad certificate
```

**Steps to Reproduce**
Use `helm` to install appmesh-controller via eks-charts 

delete the helm chart

wait for it to get deleted  - it didn't got deleted from UI delete the mesh from the UI manually

Use helm chart again install with the same name as before..

```
{"level":"info","ts":1614629616.1412656,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"virtualrouter"}
{"level":"info","ts":1614629616.141275,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"virtualrouter","worker count":3}
2021/03/01 20:13:45 http: TLS handshake error from 11.1.129.117:42638: remote error: tls: bad certificate
2021/03/01 20:13:45 http: TLS handshake error from 11.1.129.117:42642: remote error: tls: bad certificate
...
```

**Are you currently working around this issue?**
No work around found

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

```
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
appmesh-controller      appmesh-system  2               2021-03-01 20:13:21.232926148 +0000 UTC deployed        appmesh-controller-1.3.0                1.3.0
```

EKS version 1.18

EKS created via eksctl the manifest is available here https://github.com/k8s-gitops/fleet-baseline/blob/main/.eksctl/init-cluster.yaml

eksctl create -f ./eksctl/init-cluster.yaml

helm chart installed via flux2

**Comment by achevuru** [comment]
I tried "Creation -> Deletion -> Creation of Mesh with the same name" and I don't see any issue. Can you elaborate on how helm-delete of appmesh controller and a Mesh delete are related here? Are you deleting the controller and then deleting the Mesh manually via AppMesh console? `tls handshake error` shouldn't be related to a resource delete but if you can share more info on what you are trying to do then we can try it out internally and check.

**Comment by kenichi-shibata** [comment]
Yeah i tried replicating again I can't replicate this without AWS Cloudmap. I removed AWS Cloudmap and used CoreDNS default service discovery and it worked. It could be hiding an error there. But yeah I can't replicate so please feel free to close.

**Comment by achevuru** [comment]
@kenichi-shibata ServiceDiscovery mode shouldn't have an effect w.r.t Mesh create/delete. If you are creating resources using AppMesh controller but deleting or modifying them directly via console then the resources will go out of sync. We should be using controller to manage the lifecycle of AppMesh resources on the K8S cluster. If you're able to reproduce this issue again, feel free to reopen the issue.
