### ISSUE TITLE
service fails to start after mutating with agent.sock is not a socket file when enabling SDS for mTLS

### ISSUE THREAD

**Issue by caleygoff-invitae** [aws/aws-app-mesh-controller-for-k8s#448]
**Describe the bug**
When upgrading the appmesh controller to 1.3.0 and enabling the spire-service on the controller, but before actually installing the SPIRE Server and Agent. Working services on the mesh post appmesh mutation, no longer start. The service is currently dying with the following error 
```
MountVolume.SetUp failed for volume "appmesh-sds-socket-volume" : hostPath type check failed: /run/spire/sockets/agent.sock is not a socket file
```
Looking at the mutated deployment spec I can see this on the pod
```
 - hostPath:
      path: /run/spire/sockets/agent.sock
      type: Socket
    name: appmesh-sds-socket-volume
```
It seems that the `Type:` above is causing this to fail

**Steps to reproduce**
Install the appmesh-system to version 1.3.0 and update the CRD also. 
Enable the SDS service, but do not install the SPIRE agent or server just yet. 
Deploy a simple app to the mesh, and allow the controller to mutate the spec.
It should die with the above error if there is an issue.

**Expected outcome**
I was hoping for the app to turn on normally and at least report it can't reach the SDS-server. I am under the impression that the sds-agent running next to the envoy proxy on the service pod is isolated from the spire-server and spire-agent that is installed as daemonsets. 

Perhaps I need to install the daemonset and statefulsets before attempting to deploy the service with SDS enabled. 

**Environment**

* App Mesh controller version 1.3.0
* Envoy version 1.16.1.0-prod
* Are you using any integrations? X-ray, Jaeger etc. If so versions? no
* Kubernetes version 1.18
* Using EKS (yes/no), if so version? yes eks.3

**Additional Context**:
This is mentioned in slack here: https://awsappmesh.slack.com/archives/C0113RB44C9/p1614634864024200

**Comment by achevuru** [comment]
@caleygoff-invitae Yes, if controller is enabled for SDS based mtls (enable-sds=true), controller expects to find a SDS provider @ value provided in "sds-uds-path" (default set to SPIRE Agent's v0.10.0 socket path). Please refer to https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/docs/guide/troubleshooting.md#envoy-fails-to-boot-up-when-sds-based-mtls-is-enabled

**Comment by caleygoff-invitae** [comment]
thanks adding the controller fixed that for me!
