### ISSUE TITLE
App Mesh Resources deleted from AWS Management console but left dangling in EKS cluster

### ISSUE THREAD

**Issue by pulkitsapra** [aws/aws-app-mesh-controller-for-k8s#449]
**Describe the bug**
Hey! In my kubernetes cluster, I have already deleted Appmesh resources from AWS Management console but kubernetes cluster still shows those resources even though I deleted the appmesh-system namespace. When I try to delete the virtual nodes using kubectl delete virtualnodes --all --all-namespaces It stucks .
I try to dig down to virtual routers to delete them before virtual nodes but it seems they have an active route. How to cleanup AppMesh in this case

**Expected outcome**
I expect to delete App Mesh resources that are left dangling 

**Environment**

* App Mesh controller version
* Using EKS (yes/no), if so version?
* 1.18

**Additional Context**:

**Comment by achevuru** [comment]
@pulkitsapra  If you're using K8S controller to create appmesh resources, you can't delete them from the AWS console. Expectation is that the controller will manage the lifecycle of these resources. Controller will eventually sync with AWS AppMesh but this is not a recommended approach. You can remove the finalizers (using kubectl edit) on all the appmesh resources and controller will clean them up in the K8S cluster. You need the controller to be up and running to reconcile these resources, so deleting appmesh-controller (by deleting appmesh-system) namespace will not help.

**Comment by achevuru** [comment]
Closing the issue as the behavior is as designed/expected. Feel free to re-open if there are any further clarifications required (or) if any new issues are encountered.
