### ISSUE TITLE
Unable to reference Virtual Gateway in GatewayRoute definition

### ISSUE THREAD

**Issue by vodwood** [aws/aws-app-mesh-controller-for-k8s#450]
**Describe the bug**
If I am not mistaken, there is no way currently to assign a GatewayRoute to a specific VirtualGateway via CRD, while it is possible via App Mesh User Interface.

**Steps to reproduce**
1. Create namespace and mesh
2. In this namespace, create two virtual gateways with two correlating standalone envoy deployments
3. Create two gateway routes for separate applications and apply
4. Receive: "Error from server (found multiple matching virtualGateways for namespace: namespace, expecting 1 but found N"*
* Proceeds to list virtual gateways in all namespaces, even though query was kubectl -n namespace get virtualgateways

**Expected outcome**
As via UI, there needs to be a method of mapping gateway routes to specific gateways via CRD, because there might be more than one gateway in a namespace

**Environment**

* App Mesh controller version: appmesh-controller:v1.3.0
* Envoy version: aws-appmesh-envoy:v1.16.1.1-prod 
* Are you using any integrations? X-ray, Jaeger etc. If so versions? aws-xray-daemon:latest
* Kubernetes version 1.18
* Using EKS (yes/no), if so version? yes, eks.3

**Additional Context**:
This is a fairly standard use case - to allow integration testing of every application, I'm exposing every application on the mesh via a dedicated gateway, since host-based routing is not available for ingress yet.

Currently creating Service, Deployment of envoy and VirtualGateway via CRD and adding route manually via UI and it works perfectly - each gateway routes to each application that needs to be exposed outside.

**Comment by cgchinmay** [comment]
When creating Virtual Gateway and GatewayRoutes via CRD, this is the logic we have -> The virtual gateway selects namespaces using the namespaceSelector, here you can select multiple namespaces. But from namespace point of view, it is expected to have only 1 virtual gateway and all gateway routes defined in that namespace get attached to that 1 virtual gateway. In CRD's we don't add any virtual gateway reference while creating gateway route as this association is done at the namespace level. So in your case you have 2 virtual gateways pointing to one namespace and thats why the error. We would update our docs to clarify this. Here's a sample walkthrough to see Virtual Gateway Usage: 
`
https://github.com/aws/aws-app-mesh-examples/tree/main/walkthroughs/howto-k8s-ingress-gateway
`

**Comment by vodwood** [comment]
`But from namespace point of view, it is expected to have only 1 virtual gateway and all gateway routes defined in that namespace get attached to that 1 virtual gateway.`

Why? I can create N virtual gateways in one mesh, which logically represents a namespace.

`In CRD's we don't add any virtual gateway reference while creating gateway route as this association is done at the namespace level.`

I have two applications running in one namespace: app1.namespace.com and app2.namespace.com. Both applications need to be accessed from outside the mesh. What is the intended way to achieve this if not via separate gateways?

Again, I can create two separate services of type: LoadBalancer, exposing two separate stand-alone envoy deployments and assign two separate gateways to these separate envoys - let's call them app1-gateway and app2-gateway. I can then proceed to the UI and add separate routes for these two gateways. What is the purpose of disallowing this via CRD?

It would be possible to work around the current logic by using request header based routing in gateway routes - and thus having one gateway per namespace and multiple routes. This is not supported by App Mesh though.

**Comment by cgchinmay** [comment]
> Why? I can create N virtual gateways in one mesh, which logically represents a namespace.

Because a mesh can span across multiple namespaces , 1 mesh -> n namespaces, similarly 1 VG -> n namespaces. So you can have N VG in one mesh which can point to different namespaces. 

> I have two applications running in one namespace: app1.namespace.com and app2.namespace.com. Both applications need to be accessed from outside the mesh. What is the intended way to achieve this if not via separate gateways?

Would it not work if you have one Virtual Gateway and create 2 different GatewayRoutes for app1 and app2, similar to this [example](https://github.com/aws/aws-app-mesh-examples/tree/main/walkthroughs/howto-k8s-ingress-gateway). If not, would like to know what is difference between this example and your use case.

**Comment by vodwood** [comment]
`If not, would like to know what is difference between this example and your use case.`

The difference is that two _separate_ applications need to be exposed via a different set of "ingress resources" because, for one, they have different domain names: app1.namespace.com and app2.namespace.com and are otherwise separate logical components of a distributed system. They both reside in one mesh by design.

**Comment by cgchinmay** [comment]
Thanks for clarifying that, wanted to know the missing gap in the walkthrough and your use case. 
> It would be possible to work around the current logic by using request header based routing in gateway routes - and thus having one gateway per namespace and multiple routes. This is not supported by App Mesh though.

This feature is being worked on
https://github.com/aws/aws-app-mesh-roadmap/issues/232

> What is the purpose of disallowing this via CRD?

I will get back to you on this one. 

> I have two applications running in one namespace: app1.namespace.com and app2.namespace.com. Both applications need to be accessed from outside the mesh. What is the intended way to achieve this if not via separate gateways?

If these 2 apps were in different namespaces within the same mesh, then you would have been able to create 2 VGW, with 1 VGW pointing to app1.namespace1.com and the other for app2.namespace2.com. But I don't know how feasible that option is in your case, so let me check and get back to you with better ways if any which won't require you to change your design.

**Comment by vodwood** [comment]
Thank you for your replies and effort @cgchinmay !

`If these 2 apps were in different namespaces within the same mesh, then you would have been able to create 2 VGW, with 1 VGW pointing to app1.namespace1.com and the other for app2.namespace2.com`

Yes, indeed. The issue here is that by design, a service mesh is a logical boundary for a certain set of distributed services working together. In kubernetes (at least as far as I understand - maybe wrong), a namespace provides a natural extension for this logical boundary. So app mesh = namespace in most but edge cases? So inside this "logical boundary" we have many services (distributed services/microservices) and some of them are publicly accessible i.e. accessible from outside of the mesh.

If I understood you correctly:
As a workaround, we can say that for every "public" application we create a separate namespace in kubernetes and span the mesh to all these namespaces. On my end, I'm going to validate this with AWS reps.

**Comment by cgchinmay** [comment]
Hi @vodwood, to answer your questions  
> What is the purpose of disallowing this via CRD?

As I understand, the design decision is based on kubernetes permission model. So we want Gateway to control which routes can be added to it and not the other way round while creating via CRD.

> As a workaround, we can say that for every "public" application we create a separate namespace in kubernetes and span the mesh to all these namespaces. On my end, I'm going to validate this with AWS reps

Yes, you can implement it this way as a workaround.

**Comment by cgchinmay** [comment]
Hi @vodwood Let me know if you have more questions, if not will close the issue. The features such as request header based routing are being implemented and will be released in v1.4.0 
aws/aws-app-mesh-roadmap#232

**Comment by cgchinmay** [comment]
Closing this Issue as it is being tracked here : https://github.com/aws/aws-app-mesh-controller-for-k8s/issues/463. The support will be added as a part of the 1.4.0 release of the appmesh-controller
