### ISSUE TITLE
Migrate examples to aws-app-mesh-examples

### ISSUE THREAD

**Issue by nckturner** [aws/aws-app-mesh-controller-for-k8s#47]
We should move the examples to https://github.com/aws/aws-app-mesh-examples, and link to them from here.  This consolidates examples related to App Mesh and reduces the maintenance burden.

**Comment by kiranmeduri** [comment]
aws-app-mesh-examples now is up-to-date with latest supported features. I think we should prioritize deprecating example here and add a link.

**Comment by shubharao** [comment]
Dup of https://github.com/aws/aws-app-mesh-controller-for-k8s/issues/62
