### ISSUE TITLE
Upgrade CRDs to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by allamand** [aws/aws-app-mesh-controller-for-k8s#491]
**Is your feature request related to a problem?**

When deploying the CRDs using this command (from Installing the chart):

```
kubectl apply -k "github.com/aws/eks-charts/stable/appmesh-controller//crds?ref=master"
```
I get the following warning:

```
W0719 13:06:33.130081   56372 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

**Describe the solution you'd like**
Upgrade the apiextensions CRD to the v1

**Comment by cgchinmay** [comment]
@Shreya027  We do have a PR for this : https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/492
