### ISSUE TITLE
Referenced Install script is not compatible with k8s 1.13 

### ISSUE THREAD

**Issue by geremyCohen** [aws/aws-app-mesh-controller-for-k8s#50]
The [instructions for the aws-app-mesh-controller-for-ks8](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/docs/install.md) has the users run:

curl https://raw.githubusercontent.com/aws/aws-app-mesh-inject/v0.1.5/scripts/install.sh | bash

This v0.1.5 version of the install script is not compatibile with k8s 1.13.

**Comment by jansony1** [comment]
+1

**Comment by nckturner** [comment]
Fixed by #60
