### ISSUE TITLE
pre_upgrade_check script has multiple issues

### ISSUE THREAD

**Issue by apoorvanand** [aws/aws-app-mesh-controller-for-k8s#523]
**Describe the bug**
pre_upgrade_check shows passed even if kubernetes server is not running or context is not set properly. Futher validation cheks needs to be added in the *check_old_crds(), check_controller_version(), check_injector()**  function for **pre_upgrade_check** shell script.

**Steps to reproduce**
This is only reproducible for the system where kubectl context is not set or kubectl is unable to connect to api server.

- Run pre_upgrade_check.sh, if kubectl is unable to connect to api server, this script functions **check_old_crds(), check_controller_version(), check_injector()** should fail but this shows passed. The function logic needs to modified to check if kubectl is able to connect to kubernetes api server and it should fail when it receives connection refused or permission issue.
- This script should also validate whether kubectl, jq is installed. Precheck can be added in main function to validate kubectl and jq is installed.

**Expected outcome**
If kubectl is unable to connect to api server, this script functions **check_old_crds(), check_controller_version(), check_injector( ) ** should fail.The function logic needs to modified to check if kubectl is able to connect to kubernetes api server and it should fail when it receives connection refused or permission issue.

**Environment**

* App Mesh controller version - fails at pre_upgrade_check step
* Envoy version
* Are you using any integrations? X-ray, Jaeger etc. If so versions?
* Kubernetes version
* Using EKS (yes/no), if so version? yes, Can be reproduced with any kubernetes distribution.

**Additional Context**:

**Comment by melaniesifen** [comment]
Closing this as the PR for this change has been merged
