### ISSUE TITLE
ingress-envoy needs 70s to become LIVE from PRE-INITIALIZE

### ISSUE THREAD

**Issue by RafalMaleska** [aws/aws-app-mesh-controller-for-k8s#531]
**Describe the bug**

When using AppMesh the Envoy-Ingress configured by a VirtualGateway needs ca. 70s to become LIVE from PRE-INITIALIZE. When using the official AppMesh-Gateway  helm chart, this causes the envoy to get into a crash-loop after a restart.

**Steps to reproduce**

When using AppMesh with ACM/CloudMap/IRSA/AppMesh-Controllerv1.4.1/Envoyv1.9.1.1-prod 

After a VirtualGateway was created (got ARN) and the envoy-ingress pods are up an App with 4 GatewayRoutes was deployed.
When restarting the ingress-envoy-pod manually the pod gets into a crashloop. 

Workaround: 
Increase initialDelaySeconds for liveness and readiness to 70s

**Expected outcome**
Pod starts withing seconds and routes traffic

**Environment**

* App Mesh controller version 1.4.1
* Envoy version: v1.19.1.1-prod
* Are you using any integrations? X-ray, Jaeger etc. If so versions? ACM/CloudMap/IRSA
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? yes

**Additional Context**:

The pods logs say for about 70s that the pod is not fully initialized.

**Comment by suniltheta** [comment]
Checking to confirm if this is resolved since we fixed the actual issue at https://github.com/aws/aws-app-mesh-roadmap/issues/360
