### ISSUE TITLE
Set LogLevel in xray-daemon

### ISSUE THREAD

**Issue by buzzsurfr** [aws/aws-app-mesh-controller-for-k8s#545]
**Is your feature request related to a problem?**
I want to customize the log level whenever the `xray-daemon` container is added.

**Describe the solution you'd like**
Add options to inject log level to xray-daemon container.

**Describe alternatives you've considered**
Run xray-daemon as DaemonSet and point to address.

**Comment by suniltheta** [comment]
This should be available in next controller release 1.4.3+. We are good to close this issue?

**Comment by ar4096** [comment]
cc @Y0Username and @cgchinmay. Can we close this ?

**Comment by cgchinmay** [comment]
Closing this as the PR for this change is merged and it will be available in the next controller release.
