### ISSUE TITLE
Envoy ServiceAccountName

### ISSUE THREAD

**Issue by hemandee** [aws/aws-app-mesh-controller-for-k8s#550]
**Is your feature request related to a problem?**
A description of what the problem is. For example: I'm frustrated when [...]

When defining a Deployment + Appmesh configuration, serviceaccountname specified is copied to envoy proxy config. I would like to pass a custom serviceaccountname to envoy proxy to keep my IAM roles separate between proxy and my application. 
It can be replicated with https://github.com/aws/aws-app-mesh-examples/tree/main/walkthroughs/howto-k8s-fargate. 

**Describe the solution you'd like**
A description of what you want to happen.

Pass Custom Service Account Name in to be injected to Envoy Proxy config

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

Attaching it policies to the ec2 instance, but this does not work with Fargate.

**Comment by cgchinmay** [comment]
Each Pod has a proxy container and your application container. You specify serviceAccount per pod. Are you saying that you want to have a different serviceAccount for proxy container from the one used by your application container ?

**Comment by cgchinmay** [comment]
@hemandee any updates ?, if not will close this issue

**Comment by ar4096** [comment]
I think this is exactly what @hemandee is asking for @cgchinmay ? Separate service accounts for pod and proxy. It seems like a legitimate ask - to apply the least privilege principle to the proxy executable ?

**Comment by cgchinmay** [comment]
> I think this is exactly what @hemandee is asking for @cgchinmay ? Separate service accounts for pod and proxy. It seems like a legitimate ask - to apply the least privilege principle to the proxy executable ?

That does make sense and will need to explore how this can be achieved.

**Comment by EdwardXF** [comment]
We have investigated this problem, but unfortunately, different service accounts in the same pod is not currently supported by Kubernetes and you can only attach one IAM role per service account. We will further investigate this to see if there is a walk-around to implement this functionality.
