### ISSUE TITLE
Unable to update cloudmap DNS TTL

### ISSUE THREAD

**Issue by mindbergh** [aws/aws-app-mesh-controller-for-k8s#560]
**Describe the bug**
There are two issues regarding update cloudmap DNS ttl.

1. [helm expects float64](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/config/helm/appmesh-controller/templates/deployment.yaml#L77) whereas the [appmesh controller expects int64](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/cloudmap/config.go#L17):

For example, if I give a TTL of 10 in the helm release, it will be ignored by the template.

2. Even if the appmesh controller's deployment get updated to include the TTL argument, the reconcile will not update the existing cloudmap service. Looks like the [reconciler logic](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/cloudmap/resource_manager.go#L104) only takes ttl into consideration when creating a new cloudmap service but doesn't update if there is a change.

I had to manually delete the cloudmap service and let the controller reconcile to recreate one in order to apply the DNS TTL change.

**Steps to reproduce**
1. Using the helm to update the cloudmap DNS TTL.
2. The controller deployment will not be updated.
3. The DNS TTL in cloudmap service will not be updated.

**Expected outcome**
1. The helm release is able to update the cloudmap TTL of the appmesh controller deployment.
2. Appmesh controller is able to update existing cloudmap service's DNS ttl.

**Environment**

* App Mesh controller version: helm chart v1.4.4, controller: v1.4.2
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? yes

**Additional Context**:
N/A

**Comment by melaniesifen** [comment]
This issue for setting the DNS TTL has been resolved with the latest eks appmesh-controller helm chart release. This field will not update existing CloudMap services. Existing services can be updated using the [AWS CloudMap API](https://docs.aws.amazon.com/cloud-map/latest/api/API_UpdateService.html)
