### ISSUE TITLE
Support VirtualNode as provider for VirtualService

### ISSUE THREAD

**Issue by geremyCohen** [aws/aws-app-mesh-controller-for-k8s#57]
Today k8s controller does not support virtual-node as provider for virtual-service.  Would be great to get that supported in the controller.

**Comment by astrived** [comment]
Will be supported in 1.0

**Comment by M00nF1sh** [comment]
Hi, you may want to try out our GA candidate: https://github.com/aws/eks-charts/tree/master/stable/appmesh-manager. It have backwards-incompatible changes to API types.

You can currently install it by below instructions. (you need to first uninstall old appmesh objects and crds and controller/injector)
This appmesh-manager combines the functionality of controller and injector

git clone https://github.com/aws/eks-charts/tree/master/stable/appmesh-manager
kubectl apply -k github.com/aws/eks-charts/stable/appmesh-manager//crds?ref=master
helm upgrade -i appmesh-manager ./eks-charts/stable/appmesh-manager/ --namespace appmesh-system

**Comment by M00nF1sh** [comment]
closing this as it's supported in GA version.
