### ISSUE TITLE
preStopDelay doesn't work anymore with v.1.22.0.0-prod envoy image

### ISSUE THREAD

**Issue by yws-ss** [aws/aws-app-mesh-controller-for-k8s#605]
**Describe the bug**
All aws-appmesh-envoy image release versions starting from v1.22.0.0 are built as a distroless Docker image. We found that it doesn't contain any "sleep" command, which is needed by appmesh controller if we enable the flag "PreStopDelay".

https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/312/files

**Expected outcome**
Add the "sleep" command back and pod prestop hook work as usual

**Comment by suniltheta** [comment]
Hi thanks for bringing this issue to our attention. The v1.22 image is a distroless docker image, so some linux commands are missing from the image. If you want to still use v1.22 then we have a temporary workaround on how to mitigate this issue https://github.com/aws/aws-app-mesh-roadmap/issues/407#issuecomment-1122661513 by building a custom docker image.

If not you might have to switch to using the earlier Envoy image version that has sleep command inbuilt.

We will fix the next distroless docker image to contain the sleep command. Probably on v1.23.x

**Comment by suniltheta** [comment]
Should be addressed with Envoy v1.22.2.1 https://github.com/aws/aws-app-mesh-roadmap/issues/424

**Comment by suniltheta** [comment]
A new version of controller image is release with [v1.5.1](https://github.com/aws/aws-app-mesh-controller-for-k8s/releases/tag/v1.5.1) which uses v1.22.2.1 as default envoy image. I will go ahead and close this issue.
