### ISSUE TITLE
example.md: color example return 404

### ISSUE THREAD

**Issue by fmedery** [aws/aws-app-mesh-controller-for-k8s#62]
While trying to install the controller I received this error
`https://raw.githubusercontent.com/aws/aws-app-mesh-controller-for-k8s/v0.1.2/examples/color.yaml` return 404

**Comment by nckturner** [comment]
Oops!  Looks like we broke it [here](https://github.com/aws/aws-app-mesh-controller-for-k8s/commit/60ee7534df2d5484d6332b19185d2e8ac6291d1e#diff-bfebe34154a0dfd9fc7b447fc9ed74e9) when we moved to a template file.  We need an install step that works in the github docs as well as the [AWS](https://docs.aws.amazon.com/eks/latest/userguide/deploy-mesh-connected-service.html) docs.  Something like this could work: 

```
curl https://raw.githubusercontent.com/aws/aws-app-mesh-controller-for-k8s/v0.1.2/examples/color.yaml.template | sed -e 's/${APP_NAMESPACE}/appmesh-demo/g' -e 's/${MESH_NAME}/color-mesh/g' ... | kubectl apply -f -
```

**Comment by fmedery** [comment]
@nckturner I was about to propose a PR but there is also this variable : 

`${COLOR_GATEWAY_IMAGE}`

I am curious why we do not host these example images on our AWS github Repo ?

**Comment by kiranmeduri** [comment]
we don't have a good release process to keep those images up-to-date. I vote for moving this example to aws-app-mesh-examples project and inline it here https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/eks. That way users can try different examples with little additional effort after basic `git clone`.

**Comment by nckturner** [comment]
That's fine with me, but we'll need to duplicate it there, then update the AWS docs, then remove it from here.

**Comment by kiranmeduri** [comment]
@nckturner can this be resolved, given that the recommended installation is via helm-charts and then follow aws-app-mesh-examples.
