### ISSUE TITLE
v0.1.2: unable to create Virtual nodes or Virtual routers

### ISSUE THREAD

**Issue by fmedery** [aws/aws-app-mesh-controller-for-k8s#63]
The latest release does not create Virtual Routers and Virtual Services.
Error in the containers logs:

```
E0908 19:05:20.307544       1 controller.go:443] error syncing 'appmesh-demo/colorteller-black': error updating virtual node status: Operation cannot be fulfilled on virtualnodes.appmesh.k8s.aws "colorteller-black": the object has been modified; please apply your changes to the latest version and try again

I0908 19:05:20.442223       1 virtualnode.go:96] Created virtual node colorteller-blue-appmesh-demo

E0908 19:05:20.462389       1 controller.go:443] error syncing 'appmesh-demo/colorteller-blue': error updating virtual node status: Operation cannot be fulfilled on virtualnodes.appmesh.k8s.aws "colorteller-blue": the object has been modified; please apply your changes to the latest version and try again
(...)
E0908 19:07:49.287511       1 controller.go:443] error syncing 'appmesh-demo/colorteller.appmesh-demo': error creating virtual router: InvalidParameter: 1 validation error(s) found.
```

**Comment by nckturner** [comment]
The latest release was modified to run 5 goroutines instead of 1, so it could be possible you're seeing contention between them?  Are the objects not being created successfully?  I see `Created virtual node` in your logs.

**Comment by stefanprodan** [comment]
@nckturner I had the same problem with Flagger, this is how I solved it https://github.com/weaveworks/flagger/blob/master/pkg/canary/status.go#L70

**Comment by nckturner** [comment]
Thanks @stefanprodan, we should give that a try.

**Comment by fmedery** [comment]
> The latest release was modified to run 5 goroutines instead of 1, so it could be possible you're seeing contention between them? Are the objects not being created successfully at all (ignoring the error messages)? I see `Created virtual node` in your logs.

@nckturner  No the objects were not created.

@stefanprodan tx for pointing out the workaround.

**Comment by kiranmeduri** [comment]
Yes, I have seen the contention and corresponding error messages. @stefanprodan your fix should help in this case, but I believe controller code needs some TLC. 

@fmedery this contention happens when the status is being updated, however the resources should have been created.

**Comment by kiranmeduri** [comment]
There is a non-backward compatible change in CRD where virtual-router now is required and need to provide a listener. This is the reason for 

```
E0908 19:07:49.287511       1 controller.go:443] error syncing 'appmesh-demo/colorteller.appmesh-demo': error creating virtual router: InvalidParameter: 1 validation error(s) found.
```

I am working on a fix to allow old behavior that allowed virtual-service without virtual-router spec.

**Comment by nckturner** [comment]
Can this be closed? @kiranmeduri
