### ISSUE TITLE
Second Listener for Virtual Nodes

### ISSUE THREAD

**Issue by gallowaystorm** [aws/aws-app-mesh-controller-for-k8s#672]
**Is your feature request related to a problem?**
This is a problem as currently you can only have 1 listener on the virtual node crd.  AWS Virtual Nodes support two listeners now.

**Describe the solution you'd like**
I would like for the ability to have more than one listener on the Virtual Node.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by BennettJames** [comment]
Hello,

What version of the controller are you using? The restriction on the virtual node crd was [removed](https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/630/files#diff-892663d9372babdfb3540bd0f17845f1c102bb7c1de49a47f0f53a1fd03ca1ebL879) as part of a patch to support multiple listeners, and was made available starting in the v1.7.0 release.

**Comment by gallowaystorm** [comment]
We are using an older version.  I will test with at least 1.7.0.  Thanks!
