### ISSUE TITLE
PostStart hook fails if `envoyAdminAccessPort` is set

### ISSUE THREAD

**Issue by int128** [aws/aws-app-mesh-controller-for-k8s#680]
**Describe the bug**
When both `waitUntilProxyReady` feature and custom `envoyAdminAccessPort` is set, it takes 180 seconds to start a Pod.

It seems the postStart hook fails because it attempts checking port 9901 even if `envoyAdminAccessPort` is set.
I'm not sure but the envoy admin port should be set here.
https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/598/files#diff-26b9d14582894bf62b0acd264e521eec97de87f60efc791a231da8a68b3038fd

**Steps to reproduce**
Deploy the Helm chart with this values.yaml:

```yaml
sidecar:
  envoyAdminAccessPort: 9902
  waitUntilProxyReady: true
```

Create a Deployment.

The following Kubernetes events are shown:

```
Exec lifecycle hook ([sh -c if ...snip... ; fi]) for Container "envoy" in Pod "NAME(159668bc-bdc0-4dbf-b727-316f91df73cc)" failed - error: command 'sh -c if ...snip... fi' exited with 1:
...
[2023-01-26 07:05:51.385][42][error] [AppNet Agent] Polling envoy readiness failed with error: Timed out after 180
```

The envoy container log said:

```
[2023-01-26 07:02:54.004][1][error] [AppNet Agent] Unable to reach Envoy Admin port: giving up after 4 attempt(s), error: Get "http://127.0.0.1:9901/server_info": dial tcp 127.0.0.1:9901: connect: connection refused
```

Here is the postStart hook injected to the Pod:

```yaml
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - '-c'
              - >-
                if [[ $(/usr/bin/envoy --version) =~
                ([0-9]+)\.([0-9]+)\.([0-9]+)-appmesh\.([0-9]+) &&
                ${BASH_REMATCH[1]} -ge 2 || (${BASH_REMATCH[1]} -ge 1 &&
                ${BASH_REMATCH[2]} -gt 22) || (${BASH_REMATCH[1]} -ge 1 &&
                ${BASH_REMATCH[2]} -ge 22 && ${BASH_REMATCH[3]} -gt 2) ||
                (${BASH_REMATCH[1]} -ge 1 && ${BASH_REMATCH[2]} -ge 22 &&
                ${BASH_REMATCH[3]} -ge 2 && ${BASH_REMATCH[4]} -gt 0) ]]; then
                APPNET_AGENT_POLL_ENVOY_READINESS_TIMEOUT_S=180
                APPNET_AGENT_POLL_ENVOY_READINESS_INTERVAL_S=5 /usr/bin/agent
                -envoyReadiness; else echo 'WaitUntilProxyReady is not supported
                in Envoy version < 1.22.2.1'; fi
```

**Expected outcome**
The postStart hook is succeeeded and Pod starts shortly.

**Environment**

* App Mesh controller version: v1.10.0
* Envoy version: v1.22.2.1-prod
* Are you using any integrations?: No
* Kubernetes version: EKS v1.22
* Using EKS (yes/no), if so version?: Yes

**Additional Context**:
Related issue:
- https://github.com/aws/aws-app-mesh-controller-for-k8s/issues/489

**Comment by BennettJames** [comment]
Hello,

Would it be possible for you to use the `v1.24.1.0-prod` envoy image? I believe this was a fixed issue in the underlying envoy image.

**Comment by int128** [comment]
Thank you for the quick response. I will try that version.

**Comment by BennettJames** [comment]
Closing as likely fixed; can re-open if needed.
