### ISSUE TITLE
Some resources get abandoned

### ISSUE THREAD

**Issue by nckturner** [aws/aws-app-mesh-controller-for-k8s#71]
Currently, in specific circumstances (if they are renamed), certain resources get abandoned.  I know of at least virtual routers and cloud map services.  I think if the controller created the resource, then it should clean it up, so in that case we need to remember which resources we've created.  I don't think either resource supports tags, but we might be able to take advantage of the custom resource status fields.

**Comment by astrived** [comment]
This is blocking issue

**Comment by astrived** [comment]
@M00nF1sh @achevuru is this targeted for GA ?

**Comment by achevuru** [comment]
Fixed in v1.0
