### ISSUE TITLE
After modyifing the virtualrouter/virtualnode k8s manifest file it not update changes inPlace 

### ISSUE THREAD

**Issue by gaurav04** [aws/aws-app-mesh-controller-for-k8s#714]
We are managing the appMesh resource from K8s manifest file for that we installed appMesh controller in K8s. Every time when we make small changes in virtualNode or virtualRouter and run terraform again it ask for destroy and create instead of in-place upgrade. When it try to delete the resource it failed because virtualNode has dependency on VirtualRouter, VirtualService and VirtualGateway. 

```
resource "kubernetes_manifest" "virtualrouter" {

  manifest = {
    apiVersion = "appmesh.k8s.aws/v1beta2"
    kind       = "VirtualRouter"

    metadata = {
      name      = var.name
    }
    spec = {
      listeners = [
        {
          portMapping = {
            port     = 8080
            protocol = "http"
          }
        },
      ]

      routes = [
        {
          httpRoute = {
            action = {
              weightedTargets = [
                {
                  virtualNodeRef = {
                    name = var.name
                  }
                  weight = 100
                }
              ]
            }
            match = {
              prefix = "/"
            }
            retryPolicy = {
              httpRetryEvents = ["server-error", "gateway-error"]
              maxRetries      = 3
              perRetryTimeout = {
                unit  = "ms"
                value = 5000
              }
              tcpRetryEvents = ["connection-error"]
            }
          }
          name = var.name
        },
      ]
    }
  }
}
```
What we are getting:

```resource "kubernetes_manifest" "virtualrouter" {
      ~ manifest = {
          ~ spec       = {
              ~ routes    = [
                  ~ {
                      ~ httpRoute = {
                          ~ retryPolicy = {
                              ~ perRetryTimeout = {
                                  ~ value = 10000 -> 5000
                                    # (1 unchanged attribute hidden)
                                }
                                # (3 unchanged attributes hidden)
                            }
                            # (2 unchanged attributes hidden)
                        }
                        name      = "test"
                    },
                ]
                # (1 unchanged attribute hidden)
            }
            # (3 unchanged attributes hidden)
        }
      ~ object   = {
          ~ metadata   = {
              + annotations                = (known after apply)
              + creationTimestamp          = (known after apply)
              ~ deletionGracePeriodSeconds = 0 -> (known after apply)
              ~ deletionTimestamp          = "2023-07-21T09:10:32Z" -> (known after apply)
              ~ finalizers                 = [
                  - "finalizers.appmesh.k8s.aws/aws-appmesh-resources",
                ] -> (known after apply)
              + generateName               = (known after apply)
              + generation                 = (known after apply)
              + labels                     = (known after apply)
              + managedFields              = (known after apply)
                name                       = "test"
              + ownerReferences            = (known after apply)
              + resourceVersion            = (known after apply)
              + selfLink                   = (known after apply)
              ```

Plan: 1 to add, 1 to change, 1 to destroy.
```

**Expected outcome**
Plan: 0 to add, 1 to change, 0 to destroy.

**Environment**

* App Mesh controller version - 1.11
* Envoy version
* Are you using any integrations? X-ray, Jaeger etc. If so versions?
* Kubernetes version
* Using EKS (yes/no), if so version? 1.26

**Additional Context**:

**Comment by gaurav04** [comment]
Any help on this will really help. Thanks

**Comment by ysdongAmazon** [comment]
App Mesh Controller treats certain updates as requiring a replacement of the resource rather than an in-place update. `ignore_changes` attribute in lifecycle block could used to prevent Terraform from considering certain changes to the resource as needing a new resource. 
This can be helpful in situations where certain changes to a resource would normally force a new resource to be created, but where the creation of a new resource is not desirable or necessary. While if you do need new attributes to accomplish mesh deployment, perhaps this proposal is not relevant.

**Comment by gaurav04** [comment]
We want to apply those changes but in-place. During replacement, it keep trying destroy virtualrouter but not succeed because virtualservice using virtualrouter.

**Comment by ysdongAmazon** [comment]
Yes virtualService (or other dependent resource) needs to be removed at this time, before you remove the virtualRouter. Fully apply and destroy terraform config template is probably the better solution. We would also actively investigate other methods.

**Comment by conorevans** [comment]
+1 on this. For example, changing the `egressFilter` from unset to `ALLOW_ALL` causes the Mesh object to need re-creation, which obviously means literally every other object in the Mesh needs to be recreated - however you can update that property in the AWS UI without any issue.

Similar adding logging to a VirtualNode triggers recreation but the VirtualRouter references it so needs to be deleted first, but ofc the VirtualService references the VirtualRouter so needs to be deleted. All for adding logging to a VirtualNodeSpec, which again can be made in the UI.

This is okay -- albeit quite annoying -- in a dev environment when you're spinning something up, but it's really not feasible for production. Deleting all of these resources will lead to traffic downtime, all for minor changes that can be made fine in the UI

**Comment by gaurav04** [comment]
> Yes virtualService (or other dependent resource) needs to be removed at this time, before you remove the virtualRouter. Fully apply and destroy terraform config template is probably the better solution. We would also actively investigate other methods.

Yeah please let us know if you get something better solution that would really help us. We are now in Prod and seeing this kind of issue will lead to traffic downtime for this minor changes.

**Comment by ysdongAmazon** [comment]
In top of my head, the way to go is to adopt blue-green, or switch to cloudformation, but since these are only minor changes, maybe this answer isn't what you're looking for

**Comment by BennettJames** [comment]
Making resources manageable through terraform's `kubernetes_manifest` has not, historically, been something on our radar as something we target for first class support.

From some cursory research: I would guess what's happening here is that the terraform planner isn't smart enough to track object identity, so it's just working off of object diffing to determine changes. It's not immediately obvious to me how to improve upon this behavior. 

Going off on a limb, I would _guess_ (?) that there may be some way we could augment the CRD with some information about resource identity, so the terraform planner could say track that two resources across two revisions with the same name as identical and not attempt to perform a teardown first. If anyone has any thoughts / relevant documentation concerning that, we could take a look at updating the CRD's.

**Comment by gaurav04** [comment]
We replaced `kubernetes_manifest` with `kubectl_manifest` which fixed the issue

**Comment by BennettJames** [comment]
Great to hear you found a solution.

Closing; can re-open if needed.
