### ISSUE TITLE
🚨 appmesh-envoy:v1.27.0.0-prod does not run

### ISSUE THREAD

**Issue by egkelly** [aws/aws-app-mesh-controller-for-k8s#736]
**Describe the bug**
The container build for appmesh-envoy:v1.27.0.0-prod seems to be tainted as it is not built with the /controller folder. This causes the container to enter a constant CrashLoopBackoff

**Steps to reproduce**

Using the helm chart to install, set `image.tag=v1.27.2.0-prod`. Deploy the chart.

Pod is in a CrashLoopBackoff state:
```Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  82s                default-scheduler  Successfully assigned appmesh-system/appmesh-controller-778bc78c6f-7wf6m to ip-10-68-143-58.ec2.internal
  Normal   Pulled     37s (x4 over 81s)  kubelet            Container image "840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.27.2.0-prod" already present on machine
  Normal   Created    36s (x4 over 81s)  kubelet            Created container controller
  Warning  Failed     36s (x4 over 81s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/controller": stat /controller: no such file or directory: unknown
  Warning  BackOff    2s (x9 over 80s)   kubelet            Back-off restarting failed container controller in pod appmesh-controller-778bc78c6f-7wf6m_appmesh-system(dbb988fa-b516-4d2c-a1cd-43f41d44b81f)
```

I pulled a debug container for the image to poke around in the container and found no `/controller` at the root. The only files available at the root are as follows:
```
sh-4.2# cd 
THIRD-PARTY-LICENSES.txt          aws_appmesh_aggregate_stats.wasm  dev/                              health_check.sh                   proc/                             tmp/                              var/
agent-resources/                  bin/                              etc/                              lib64/                            sys/                              usr/
```

**Expected outcome**
The appmesh-controller pod comes up successfully.

**Environment**

* AppMesh controller version: v1.27.0.0. Also tried with v1.27.2.0
* Envoy version: 1.27.0.0
* Kubernetes version: 1.26
* EKS version: eks.7

**Additional Context**:

**Comment by joesbigidea** [comment]
Hi! It sounds like you may be specifying the Envoy sidecar image instead of the controller image. The controller image is specified in helm with image.repository and image.tag. 

The Envoy sidecar image is deployed with your workloads, not to run the controller. It's specified with sidecar.image.repository and sidecar.image.tag. If you're looking to run AppMesh with Envoy 1.27.0 then set sidecar.image.tag to the desired version.

**Comment by egkelly** [comment]
Ah yep that makes a lot more sense. Thanks!
