### ISSUE TITLE
Override APPMESH_EGRESS_IGNORED_PORTS in injected proxyInit container

### ISSUE THREAD

**Issue by imishchuk-carbon** [aws/aws-app-mesh-controller-for-k8s#751]
Hey, team.

**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Ability to override `APPMESH_EGRESS_IGNORED_PORTS` in injected `proxyInit` container.

Current default value 

```
- name: APPMESH_EGRESS_IGNORED_PORTS
   value: "22"
```

But I would like to add additional ports to this env var, like

```
- name: APPMESH_EGRESS_IGNORED_PORTS
   value: "22,443,5432"
```

**Describe alternatives you've considered**
Alternative is to use 

```
egressFilter:
    type: ALLOW_ALL
```

and control egress in NACL, for example, but I'd prefer to have this controlled on EKS side

Another option I'm looking into is using mutating webhook, yet it's unclear for now, how to target that specific environmental variable.

Thank you.

**Comment by bendu** [comment]
Hello @imishchuk-carbon 

Thanks for reaching out. The controller already supports overriding the ignored ports using the "appmesh.k8s.aws/egressIgnoredPorts" annotation on the pod/deployment yaml.

Here's an [example](https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/313) of someone someone setting the annotation

**Comment by imishchuk-carbon** [comment]
Gotcha.

Thank you.
